version: "3.9"

services:
  mom:
    image: njmittet/alpine-activemq
    networks:
      - main

  section-1-control-station:
    image: control-station:0.0.1-SNAPSHOT
    environment:
      SECTION: 1

  section-1-timing-station-1:
    image: timing-station:0.0.1-SNAPSHOT
    environment:
      SECTION: 1
      TIMING_STATION: 1
networks:
  main:
    driver: bridge
